### ISSUE TITLE
Set default_scope for Post

### ISSUE THREAD

**Issue by cllns** [RefugeRestrooms/refuge_housing#16]
Right now, people can still go to a post that's not confirmed by typing the next ID in the URL. Instead, in `posts#show`, we should make sure to only find Posts that are active.

To make sure we don't always have to remember to do that, we should consider changing the `active` scope to be the `default_scope`.

(I think this also means that after a post expires, the URL to that post will still work, though there won't be any links to it on the site. We don't want that)

**Comment by mi-wood** [comment]
Seeing a lot of "don't use default_scope unless you really have to"s when I search for setting default_scope to an existing scope. Looks like it gets applied to object initialization causing a new post to be active without confirmation. Is there a different way to hide these? I vaguely remember using active/inactive as a cheap, easy way to hide things from search, even if they can be viewed.

**Comment by cllns** [comment]
Yea, I actually agree now that `default_scope` might not be the way to go. We can just check in the `show` action for PostsController.
