### ISSUE TITLE
offered showing up in needed

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refuge_housing#19]
I entered a offered post, and its showing up on on the needed filter too. Its showing up in both places.

<img width="1292" alt="screen shot 2015-11-04 at 11 33 12 am" src="https://cloud.githubusercontent.com/assets/5265597/10949480/f129030e-82e7-11e5-8971-f6f36d603f93.png">

**Comment by cllns** [comment]
Thanks @tkwidmer, fixed it and now there's a spec for it too :)
