### ISSUE TITLE
SEO improvements.

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refuge_housing#7]
"Refuge" by itself is not very searchable to find this site. It'd probably be better to have "Trans Housing" in the title/domain in some way. Optimally, it would be nice to get a redirect from transhousingnetwork.com, but I've reached out to see if they want to collaborate and haven't gotten a response. If anyone knows who runs that tumblr, it would be rad to talk to them :)

**Comment by tkwidmer** [comment]
we can make the url transhousing.refuge.lgbt that might help. Then the title becomes "Trans Housing Refuge"
